accounts/urls.py
from django.urls import path

from accounts.views import SignUpView, ProfileTemplateView

app_name = "accounts"

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
    path("profile/", ProfileTemplateView.as_view(), name="profile"),
]

blog/urls.py
from django.urls import path

from blog.views import BlogListView, BlogDetailView, CommentCreateView

app_name = "blog"

urlpatterns = [
    path("", BlogListView.as_view(), name="blog-page"),
    path("<int:pk>/comment/", CommentCreateView.as_view(), name="comment"),
    path("<int:pk>/", BlogDetailView.as_view(), name="detail")
]

contact/urls.py
from django.urls import path

from contact.views import ContactCreateView, AboutUsView

app_name = "contact"

urlpatterns = [
    path("", ContactCreateView.as_view(), name="contact"),
    path("about-us/", AboutUsView.as_view(), name="about-us"),
]

djangoProjectFinal_exam/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.template.context_processors import i18n
from django.urls import path, include

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
    path("", include("home.urls", namespace="home")),
    path("products/", include("products.urls", namespace="products")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("contact/", include("contact.urls", namespace="contact")),
)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from home.views import IndexTemplateView

app_name = "home"


urlpatterns = [
    path("", IndexTemplateView.as_view(), name="page"),
]

products/urls.py
from django.urls import path

from products.views import ProductTemplateView, ProductDetailView, update_wishlist, WishlistView, update_cart, \
    CartListView

app_name = "products"

urlpatterns = [
    path("", ProductTemplateView.as_view(), name="page"),
    path("wishlist/", WishlistView.as_view(), name="wishlist"),
    path("cart/", CartListView.as_view(), name="cart"),
    path("<int:pk>/cart/", update_cart, name="update-cart"),
    path("<int:pk>/wishlist", update_wishlist, name="update-wishlist"),
    path("products/<int:pk>", ProductDetailView.as_view(), name="product_detail"),
]

templates/layouts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">
<head>
    <link rel="icon" href="{% static 'images/apple_icon.png' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
    <!-- Optional theme -->
    <link rel="stylesheet" href="owlcarousel/owl.carousel.min.css">
    <link rel="stylesheet" href="owlcarousel/owl.theme.default.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css"
          integrity="sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ" crossorigin="anonymous">
    {% block extra_css %}{% endblock %}
    <style>

        html,
        body {
            height: 100%;
            font-family: "Nunito Sans", sans-serif;
        }

        h1 h2 h3 h4 h5 h6 {
            font-family: sans-serif;
        }

        a:hover,
        a:focus {
            outline: none;
            color: blue;
        }

        h2 {
            font-size: 55px;
        }

        a {
            font-size: 25px;
            color: black;
        }

        ul,
        ol {
            padding: 0;
            margin: 0;
            list-style-type: none;
        }

        .search_items {
            text-align: center;
            padding: 15px 0;
        }

        .product__pagination {
            padding-top: 25px;
            text-align: center;
        }

        .product__pagination a {
            display: inline-block;
            font-size: 16px;
            font-weight: 700;
            color: #111111;
            height: 30px;
            width: 30px;
            border: 1px solid transparent;
            border-radius: 50%;
            line-height: 30px;
            text-align: center;
        }

        .heart :hover {
            color: red;
        }

        .product__pagination a.active {
            border-color: #111111;
        }

        .product__pagination a:hover {
            border-color: #111111;
        }

        .product__pagination span {
            display: inline-block;
            font-size: 16px;
            font-weight: 700;
            color: #111111;
            padding-left: 10px;
            padding-right: 15px;
        }

        #blog-page h1 {
            color: orange;
            padding-top: 15%;
            padding-bottom: 15%;
            font-weight: bold;
            font-size: 100px;
            font-family: sans-serif;
            background-image: url({% static 'images/blogg.jpg'%})
        }

        .carousel-inner img {
            height: 1000px !important;
        }

        #hint_id_username, #hint_id_password1, #hint_id_password2 {
            display: none;
        }
    </style>
</head>
<body>
{% include 'layouts/header.html' %}
{% block content %}
{% endblock %}
{% include "layouts/footer.html" %}

<script src="{% static 'js/jquery-' %}3.6.0.min.js"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.js' %}"></script>
<script src="{% static 'js/main.js' %}3.3.1.min.js"></script>
<script src="{% static 'js/jquery-' %}3.3.1.min.js"></script>
{% block extra_js %}
{% endblock %}
</body>
</html>

templates/layouts/footer.html
{% load static %}
<footer class="bg-dark text-center text-white">
    <div class="bg-dark sans" style="background-color: rgba(0, 0, 0, 0.2);">
        <h6>Want to find out more about <a href="{% url 'contact:about-us' %}">us</a> ?</h6>
        <h6>Or call just to this number +998905810061 USA</h6>
    </div>
    <div class="bg-dark text-center p-3 sans" style="background-color: rgba(0, 0, 0, 0.2);">
        <h6>© 2021 Apple Store</h6>
        <a style="font-family: sans-serif" class="text-white sans" href="https://apple.com/">apple.com</a>
    </div>
    <!-- Copyright -->
    <script src="{% static 'js/jquery-' %}3.6.0.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.js' %}"></script>
    <script src="{% static 'js/main.js' %}3.3.1.min.js"></script>
    <script src="{% static 'js/jquery-' %}3.3.1.min.js"></script>
    <script src="{% static 'js/jquery-' %}3.3.1.min.js"></script>
</footer>

templates/layouts/header.html
{% load my_tags %}
<!DOCTYPE html>
{% load static %}
{% load i18n %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Apple.com</title>
</head>
<div class="text-right bg-dark">
    <div class="head pb-2">
        {% if request.user.is_authenticated %}
            <p class="text-center text-white">Welcome {{ user.username }} !</p>
            <p class="text-white text-center">Thank you !</p>
            <div style="margin-left: 7px; margin-bottom: 5px" class="mb-3">
                <div class="lang_icons">
                    <a class="text-light" href="/en/"><i><img width="3%"
                                                              src="{% static 'images/flags/united-states.png' %}"
                                                              alt=""></i></a>
                    <a class="text-light" href="/ru/"><i><img width="3%" src="{% static 'images/flags/russia.png' %}"
                                                              alt=""></i></a>
                    <a class="text-light" href="/uz/"><i><img width="3%"
                                                              src="{% static 'images/flags/uzbekistan.png' %}"
                                                              alt=""></i></a>
                </div>
            </div>
            <a style="color: whitesmoke; margin-left: 5px" href="{% url "logout" %}"
               class="navbar-brand btn btn-secondary">Log Out</a>
            <a style="color: whitesmoke" href="#" class="navbar-brand btn btn-secondary">History</a>
            <a style="color: whitesmoke" href="{% url 'accounts:profile' %}" class="navbar-brand btn btn-secondary">Profile</a>
        {% else %}
            <p style="margin-left: 5px" class="text-white">You are not logged in as our client ! pls login</p>
            <a style="color: whitesmoke; margin-left: 5px" href="{% url 'login' %}"
               class="navbar-brand btn btn-secondary">Log In</a>
            <a style="color: whitesmoke" href="{% url 'accounts:signup' %}" class="navbar-brand btn btn-secondary">Sign Up</a>
        {% endif %}
    </div>
</div>
<nav class="navbar navbar-light bg-light">
    <div class="container">
        <img src="{% static 'images/apple_icon.png' %}" alt="" height="85px" width="85px">
        {% url 'home:page' as lang_link %}
        <a class="navbar-brand" href="{{ lang_link }}" {% if request.path == lang_link %}style="color: red"{% endif %}>Home</a>
        {% url 'products:page' as lang_link %}
        <a class="navbar-brand" href="{{ lang_link }}"
           {% if request.path == lang_link %}style="color: red"{% endif %}>Products</a>
        {% url 'blog:blog-page' as lang_link %}
        <a class="navbar-brand" href="{{ lang_link }}"
           {% if request.path == lang_link %}style="color: red"{% endif %}>Blog</a>
        {% url 'contact:about-us' as lang_link %}
        <a class="navbar-brand" href="{{ lang_link }}"
           {% url 'contact:about-us' as lang_link %}
           {% if request.path == lang_link %}style="color: red"{% endif %}>About</a>
        {% url 'contact:contact' as lang_link %}
        <a class="navbar-brand" href="{{ lang_link }}"
           {% if request.path == lang_link %}style="color: red"{% endif %}>Contact</a>
        <div>
            {% get_cart_info request as cart_info %}
            <a class="heart pr-2" href="{% url 'products:wishlist' %}"><i class="bi-heart"></i></a>
            <a class="bag pr-1" href="{% url 'products:cart' %}"><i class="bi-bag"></i></a><span>{{ cart_info.0 }}</span><span> ${{ cart_info.1 }}</span>
        </div>
    </div>
</nav>
</html>