accounts/urls.py
from django.urls import path

from accounts.views import SignUpView, ProfileTemplateView

app_name = "accounts"

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
    path("profile/", ProfileTemplateView.as_view(), name="profile"),
]

blog/urls.py
from django.urls import path

from blog.views import BlogListView, BlogDetailView, CommentCreateView

app_name = "blog"

urlpatterns = [
    path("", BlogListView.as_view(), name="blog-page"),
    path("<int:pk>/comment/", CommentCreateView.as_view(), name="comment"),
    path("<int:pk>/", BlogDetailView.as_view(), name="detail")
]

contact/urls.py
from django.urls import path

from contact.views import ContactCreateView, AboutUsView

app_name = "contact"

urlpatterns = [
    path("", ContactCreateView.as_view(), name="contact"),
    path("about-us/", AboutUsView.as_view(), name="about-us"),
]

home/urls.py
from django.urls import path

from home.views import IndexTemplateView

app_name = "home"


urlpatterns = [
    path("", IndexTemplateView.as_view(), name="page"),
]

products/urls.py
from django.urls import path

from products.views import ProductTemplateView, ProductDetailView, update_wishlist, WishlistView, update_cart, \
    CartListView

app_name = "products"

urlpatterns = [
    path("", ProductTemplateView.as_view(), name="page"),
    path("wishlist/", WishlistView.as_view(), name="wishlist"),
    path("cart/", CartListView.as_view(), name="cart"),
    path("<int:pk>/cart/", update_cart, name="update-cart"),
    path("<int:pk>/wishlist", update_wishlist, name="update-wishlist"),
    path("products/<int:pk>", ProductDetailView.as_view(), name="product_detail"),
]

blog/models.py
from django.db import models
from django.utils.translation import gettext as _


class AuthorModel(models.Model):
    full_name = models.CharField(max_length=54, verbose_name=_("full name"))
    avatar = models.ImageField(upload_to="media/blog/avatars", verbose_name=_("avatar"))

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name

    class Meta:
        verbose_name = _("author")
        verbose_name_plural = _("authors")


class PostModel(models.Model):
    title = models.CharField(max_length=255, verbose_name=_("title"))
    image = models.ImageField(upload_to="media/blog", verbose_name=_("image"))
    author = models.ForeignKey(AuthorModel, related_name="posts", on_delete=models.PROTECT, verbose_name=_("author"))

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _("post")
        verbose_name_plural = _("posts")


class PostCommentModel(models.Model):
    post = models.ForeignKey(PostModel, related_name="comments", on_delete=models.CASCADE, verbose_name=_("post"))

    name = models.CharField(max_length=32, verbose_name=_("name"))
    email = models.EmailField(verbose_name=_("email"))
    phone = models.CharField(max_length=13)
    comment = models.TextField(verbose_name=_("comment"))

    created_at = models.DateTimeField(auto_now_add=True, null=True)

contact/models.py
from django.db import models
from django.utils.translation import gettext as _


class ContactModel(models.Model):
    name = models.CharField(max_length=25, verbose_name=_("name"))
    email = models.EmailField(max_length=50, verbose_name=_("email"))
    phone = models.CharField(max_length=12, verbose_name=_("phone"))
    message = models.TextField(verbose_name=_("message"))

    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_("created at"))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "contact"
        verbose_name_plural = "contacts"


class AboutUsModel(models.Model):
    about_email = models.EmailField(max_length=50, verbose_name=_("about_email"))
    about_message = models.TextField(verbose_name=_("about_message"))

    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_("created at"))

    def __str__(self):
        return self.about_email

    class Meta:
        verbose_name = "about"
        verbose_name_plural = "abouts"

products/models.py
from django.contrib.auth import get_user_model
from django.db import models, IntegrityError
from django.utils import timezone
from django.utils.translation import gettext as _

UserModel = get_user_model()


class CategoryModel(models.Model):
    title = models.CharField(max_length=15, verbose_name=_("category"))

    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_("created at"))

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _("category")
        verbose_name_plural = _("categories")


class ColorModel(models.Model):
    title = models.CharField(max_length=32, verbose_name=_("code"))

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _("color")
        verbose_name_plural = _("colors")


class ProductTagModel(models.Model):
    title = models.CharField(max_length=32, verbose_name=_('title'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created at'))

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _('product tag')
        verbose_name_plural = _('product tags')


class PriceFilterModel(models.Model):
    min = models.FloatField(default=0, verbose_name=_("min"))
    max = models.FloatField(default=0, verbose_name=_("max"))

    def __float__(self):
        return self.min + self.max

    class Meta:
        verbose_name = _("price")
        verbose_name_plural = _("prices")


class ProductModel(models.Model):
    title = models.CharField(max_length=50, verbose_name=_("title"))
    image = models.ImageField(upload_to="products", verbose_name=_("products"))
    price = models.FloatField(default=0, verbose_name=_("price"))
    rate = models.CharField(max_length=2, null=True, blank=True, verbose_name=_("rate"))
    discount = models.PositiveSmallIntegerField(default=0)
    short_description = models.CharField(max_length=255, verbose_name=_("short description"))
    long_description = models.CharField(max_length=255, verbose_name=_("long description"))

    category = models.ForeignKey(
        CategoryModel,
        on_delete=models.PROTECT,
        related_name="products",
        verbose_name=_("category")
    )
    color = models.ManyToManyField(
        ColorModel,
        related_name="products",
        verbose_name=_("color")
    )
    tag = models.ManyToManyField(
        ProductTagModel,
        related_name="products",
        verbose_name=_("tag")
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_("created at")
    )

    def is_discount(self):
        return self.discount != 0

    def get_price(self):
        if self.discount:
            return (100 - self.discount) / 100 * self.price
        return self.price

    def is_new(self):
        return (timezone.now() - self.created_at).days <= 3

    def get_related(self):
        return self.category.products.order_by('-pk').exclude(pk=self.pk)[:4]

    def __str__(self):
        return self.title

    @staticmethod
    def get_from_cart(cart):
        return ProductModel.objects.filter(pk__in=cart)

    class Meta:
        verbose_name = _("product")
        verbose_name_plural = _("products")


class WishlistModel(models.Model):
    user = models.ForeignKey(UserModel, on_delete=models.CASCADE, related_name="wishlist")
    product = models.ForeignKey(ProductModel, on_delete=models.CASCADE, related_name="wishlist")

    def __str__(self):
        return f"{self.user.get_full_name()}| {self.product.title}"

    @staticmethod
    def add_or_delete(user, product):
        try:
            WishlistModel.objects.create(user=user, product=product)
        except IntegrityError:
            WishlistModel.objects.get(user=user, product=product).delete()

    class Meta:
        verbose_name = "wishlist"
        verbose_name_plural = "wishlists"
        unique_together = "user", "product"

blog/forms.py
from django import forms

from blog.models import PostCommentModel


class CommentModelForm(forms.ModelForm):
    class Meta:
        model = PostCommentModel
        exclude = ["post", "created_at"]

contact/forms.py
from django import forms

from contact.models import ContactModel, AboutUsModel


class ContactModelForm(forms.ModelForm):
    class Meta:
        model = ContactModel
        exclude = ["created_at"]


class AboutUsModelForm(forms.ModelForm):
    class Meta:
        model = AboutUsModel
        exclude = ["created_at"]

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views.generic import ListView, DetailView, CreateView

from blog.forms import CommentModelForm
from blog.models import PostModel


class BlogListView(ListView):
    template_name = "blog.html"
    model = PostModel
    context_object_name = "blog_products"

    def get_queryset(self):
        products = PostModel.objects.all()
        return products


class BlogDetailView(LoginRequiredMixin, DetailView):
    template_name = "blog_detail.html"
    model = PostModel


class CommentCreateView(CreateView):
    form_class = CommentModelForm

    def form_valid(self, form):
        form.instance.post = get_object_or_404(PostModel, pk=self.kwargs.get("pk"))
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("blog:detail", kwargs={"pk": self.kwargs.get("pk")})

contact/views.py
from django.urls import reverse
from django.views.generic import TemplateView, CreateView

from contact.forms import ContactModelForm, AboutUsModelForm
from contact.models import ContactModel


class ContactCreateView(CreateView):
    template_name = "contact.html"
    form_class = ContactModelForm

    def get_success_url(self):
        return reverse("home:page")


class AboutUsView(CreateView):
    template_name = "about.html"
    form_class = AboutUsModelForm

    def get_success_url(self):
        return reverse("home:page")

home/views.py
from django.shortcuts import render
from django.views.generic import ListView, TemplateView

from products.models import ProductModel


class IndexTemplateView(ListView):
    model = ProductModel
    template_name = "home.html"
    context_object_name = "products"

products/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Min, Max
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import TemplateView, ListView, DetailView

from products.models import CategoryModel, ColorModel, ProductTagModel, PriceFilterModel, ProductModel, WishlistModel


class ProductTemplateView(LoginRequiredMixin, ListView):
    paginate_by = 6
    model = ProductModel
    template_name = "products.html"

    def get_context_data(self, **kwargs):
        context = super(ProductTemplateView, self).get_context_data(**kwargs)
        context['categories'] = CategoryModel.objects.all()
        context['category_name'] = CategoryModel
        context['colors'] = ColorModel.objects.all()
        context['tags'] = ProductTagModel.objects.all()
        context['prices'] = PriceFilterModel.objects.all()
        context["min_price"] = ProductModel.objects.aggregate(Min("price")).values()
        context["max_price"] = ProductModel.objects.aggregate(Max("price")).values()
        return context

    def get_queryset(self):
        products = ProductModel.objects.order_by("category")
        q = self.request.GET.get("q")
        if q:
            products = ProductModel.objects.filter(title__icontains=q)
        cat = self.request.GET.get("cat")
        if cat:
            products = ProductModel.objects.filter(category_id=cat)
        color = self.request.GET.get("color")
        if color:
            products = ProductModel.objects.filter(color__id=color)
        tag = self.request.GET.get("tag")
        if tag:
            products = ProductModel.objects.filter(tag__id=tag)
        price_filter_min = self.request.GET.get("min")
        price_filter_max = self.request.GET.get("max")
        if price_filter_min and price_filter_max:
            products = ProductModel.objects.aggregate(Min("real_price"), Max("real_price")).values()
        return products


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = ProductModel
    template_name = "product-detail.html"
    context_object_name = "product"


class WishlistView(LoginRequiredMixin, ListView):
    template_name = "wishlist.html"
    context_object_name = "wishlist_products"

    def get_queryset(self):
        return ProductModel.objects.filter(wishlist__user=self.request.user)


class CartListView(ListView):
    template_name = 'cart.html'
    context_object_name = 'cart_objects'

    def get_queryset(self):
        cart = self.request.session.get('cart', [])
        return ProductModel.get_from_cart(cart)


@login_required
def update_wishlist(request, pk):
    product = get_object_or_404(ProductModel, pk=pk)
    WishlistModel.add_or_delete(request.user, product)

    return redirect(request.GET.get("next", "/"))


def update_cart(request, pk):
    product = get_object_or_404(ProductModel, pk=pk)
    cart = request.session.get("cart", [])
    if product.pk in cart:
        cart.remove(product.pk)
    else:
        cart.append(product.pk)
    request.session["cart"] = cart
    print(request.session["cart"])

    return redirect(request.GET.get("next", "/"))

templates/cart.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load my_tags %}
{% block content %}
    <div style="background-color: ghostwhite" id="about-title" class="p-5">
        <div class="container p-5">
            <h1 style="font-weight: bold; font-size: 50px; font-family: sans-serif;">Cart</h1>
        </div>
        <div class="container">
            <div class="row mt-5">
                {% for i in object_list %}
                    <div class="col-4 pb-5">
                        <div class="card" style="width: 18rem; height: 100%">
                            <img class="card-img-top" src="{{ i.image.url }}" alt="Card image cap" width="100%"
                                 height="50%">
                            <div class="card-body">
                                <a href="{% url 'products:product_detail' pk=i.pk %}"
                                   class="card-title">{{ i.title }}</a>
                                {% if i.is_new %}<span class="text-danger"> <i>
                                    <img width="10%" src="{% static 'images/new.png' %}" alt="">
                                </i></span>{% endif %}
                                <p class="card-text">{{ i.short_description }}</p>
                            </div>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item bold">${{ i.price }}{% if i.discount %}<span
                                        class="text-danger"> %{{ i.discount }}</span>
                                {% endif %}</li>
                            </ul>
                            <div class="card-body">
                                {% if i|in_wishlist:request.user %}
                                    <a href="{% url 'products:update-wishlist' pk=i.pk %}?next={{ request.path }}"
                                       class="heart card-link"><i><img width="10%" src="{% static 'images/heart.png' %}"
                                                                       alt=""></i></a>
                                {% else %}
                                    <a href="{% url 'products:update-wishlist' pk=i.pk %}?next={{ request.path }}"
                                       class="heart card-link"><i class="bi-heart"></i></a>
                                {% endif %}
                                <a href="{% url 'products:update-cart' pk=i.pk %}?next={{ request.path }}"
                                   class="card-link">
                                    {% if i|in_cart:request %}
                                        <i class="bi-cart-x"></i>
                                    {% else %}
                                        <i class="bi-cart-plus"></i>
                                    {% endif %}
                                </a>
                                <a href=""
                                   class="card-link"><i class="bi-star"></i></a><span
                                    class="bold">{{ i.rate }}</span>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    <div class="container text-center">
        {% get_cart_info request as cart_info %}
        <h3>Product items: {{ cart_info.0 }}</h3>
        <h3>Total: ${{ cart_info.1 }} </h3>
        <a href="{% url 'accounts:profile' %}" class="btn btn-dark">Place order</a>
    </div>
    </div>
{% endblock %}

templates/home.html
{% extends "layouts/base.html" %}
{% load my_tags %}
{% load static %}
{% block content %}
    <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="d-block w-100" src="{% static 'images/banner-1.jpg' %}" alt="First slide">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="{% static 'images/watch-2021.jpg' %}" alt="Second slide">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="{% static 'images/mackbook-blog.jpg' %}" alt="Third slide">
            </div>
        </div>
    </div>
    <!-- Carousel wrapper -->
    {#    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">#}
    {#        <ol class="carousel-indicators">#}
    {#            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>#}
    {#            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>#}
    {#            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>#}
    {#        </ol>#}
    {#        <div class="carousel-inner">#}
    {#            <div class="carousel-item active">#}
    {#                <img class="d-block w-100" src="{% static 'images/banner-1.jpg' %}" alt="First slide">#}
    {#            </div>#}
    {#            <div class="carousel-item">#}
    {#                <img class="d-block w-100" src="{% static 'images/watch-2021.jpg' %}" alt="Second slide">#}
    {#            </div>#}
    {#            <div class="carousel-item">#}
    {#                <img class="d-block w-100" src="{% static 'images/mackbook-blog.jpg' %}" alt="Third slide">#}
    {#            </div>#}
    {#        </div>#}
    {#        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">#}
    {#            <span class="carousel-control-prev-icon" aria-hidden="true"></span>#}
    {#            <span class="sr-only">Previous</span>#}
    {#        </a>#}
    {#        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">#}
    {#            <span class="carousel-control-next-icon" aria-hidden="true"></span>#}
    {#            <span class="sr-only">Next</span>#}
    {#        </a>#}
    {#    </div>#}
    <div class="banner">
    </div>
    <div id="banner">
        <div class="container mt-5">
            <div class="row">
                <div class="col">
                    <img src="{% static 'images/13.jpg' %}" alt="" width="100%" height="85%">
                </div>
                <div style="font-family: sans-serif" class="col m-5">
                    <h1 style="color: lightskyblue">About our Iphone13Pro</h1>
                    <p>Lorem Ipsum Dollar sit amet Lorem Ipsum Dollar sit amet Lorem Ipsum Dollar sit amet Lorem Ipsum
                        Dollar sit amet Lorem Ipsum Dollar sit ametLorem Ipsum Dollar sit ametLorem Ipsum Dollar sit
                        ametLorem Ipsum Dollar sit ametLorem Ipsum Dollar sit ametLorem Ipsum Dollar sit ametLorem Ipsum
                        Dollar sit ametLorem Ipsum Dollar sit ametLorem Ipsum Dollar sit ametLorem Ipsum Dollar sit
                        amet</p>
                    <p>Lorem Ipsum Dollar sit amet Lorem Ipsum Dollar sit amet Lorem Ipsum Dollar sit amet Lorem Ipsum
                        Dollar sit amet Lorem Ipsum Dollar sit ametLorem Ipsum Dollar sit ametLorem Ipsum Dollar sit
                        ametLorem Ipsum Dollar sit ametLorem Ipsum Dollar sit ametLorem Ipsum Dollar sit ametLorem Ipsum
                        Dollar sit ametLorem Ipsum Dollar sit ametLorem Ipsum Dollar sit ametLorem Ipsum Dollar sit
                        amet</p>
                </div>
            </div>
        </div>
    </div>
    <div id="trend_products" class="bg-light">
        <hr style="background-color: lightskyblue; padding-bottom: 10px">
        <div class="container mb-5">
            <h1 style="font-weight: bold; font-size: 50px; font-family: sans-serif">Today's Trendy Products</h1>
        </div>
        <div class="container">
            <div class="row">
                {% for i in products %}
                    {% if i.is_new %}
                        <div class="col-4 pb-5">
                            <div class="card" style="width: 18rem; height: 100%">
                                <img class="card-img-top" src="{{ i.image.url }}" alt="Card image cap" width="100%"
                                     height="50%">
                                <div class="card-body">
                                    <a href="{% url 'products:product_detail' pk=i.pk %}"
                                       class="card-title">{{ i.title }}</a><span style="margin-left: 5px"><i><img
                                        width="10%"
                                        src="{% static 'images/new.png' %}" alt=""></i></span>
                                    <p class="card-text">{{ i.short_description }}</p>
                                </div>
                                <ul class="list-group list-group-flush">
                                    <li class="list-group-item bold">${{ i.price }} {% if i.is_discount %}<span
                                            class="text-danger">%{{ i.discount }}</span>{% endif %}</li>
                                </ul>
                                <div class="card-body">
                                    {% if i|in_wishlist:request.user %}
                                        <a href="{% url 'products:update-wishlist' pk=i.pk %}?next={{ request.path }}"
                                           class="heart card-link"><i><img width="10%"
                                                                           src="{% static 'images/heart.png' %}"
                                                                           alt=""></i></a>
                                    {% else %}
                                        <a href="#" class="heart card-link"><i class="bi-heart"></i></a>
                                    {% endif %}
                                    <a href="{% url 'products:update-cart' pk=i.pk %}?next{{ request.path }}" class="card-link">{% if i|in_cart:request %}
                                        <i class="bi-cart-x"></i>
                                    {% else %}
                                        <i class="bi-cart-plus"></i>
                                    {% endif %}</a>
                                    <a class="card-link"><i class="bi-star"></i></a><span
                                        class="bold">{{ i.rate }}</span>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
        <a href="{% url 'products:page' %}">
            <h1 class="mt-5 text-center">See more...</h1>
        </a>
        <div id="team">
            <div class="team bg-secondary pb-5">
                <hr style="background-color: lightskyblue; padding-bottom: 10px">
                <div class="container">
                    <div class="row d-flex justify-content-center">
                        <div class="col-md-10 col-xl-8 text-center">
                            <h3 class="mb-4">Meet Our Teem</h3>
                            <p class="mb-4 pb-2 mb-md-5 pb-md-0">
                                The founders of our company. Who devoted more hard-work to the establishment of this
                                company
                            </p>
                        </div>
                    </div>

                    <div class="row text-center">
                        <div class="col-4 mb-5 mb-md-0">
                            <div style="width: 100%" class="card testimonial-card">
                                <div class="card-up" style="background-color: #9d789b;"></div>
                                <div class="avatar mx-auto bg-white">
                                    <img
                                            src="{% static "images/team-members/Steve-Jobs-250x286.webp" %}"
                                            class="rounded-circle img-fluid"
                                    />
                                </div>
                                <div class="card-body">
                                    <h4 class="mb-4">Steve Jobs</h4>
                                    <hr/>
                                    <p class="dark-grey-text mt-4">
                                        Founder of the company
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="col-4 mb-5 mb-md-0">
                            <div style="width: 100%" class="card testimonial-card">
                                <div class="card-up" style="background-color: #9d789b;"></div>
                                <div class="avatar mx-auto bg-white">
                                    <img
                                            src="{% static "images/team-members/Ronald_Wayne.jpg" %}"
                                            class="rounded-circle img-fluid"
                                    />
                                </div>
                                <div class="card-body">
                                    <h4 class="mb-4">Ronald Wayne</h4>
                                    <hr/>
                                    <p class="dark-grey-text mt-4">
                                        Co-Founder of the company
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="col-4 mb-0 mb-md-0">
                            <div style="width: 100%" class="card testimonial-card">
                                <div class="card-up" style="background-color: #9d789b;"></div>
                                <div class="avatar mx-auto bg-white">
                                    <img
                                            src="{% static "images/team-members/Steve_Wozniak.jpg" %}"
                                            class="rounded-circle img-fluid"
                                    />
                                </div>
                                <div class="card-body">
                                    <h4 class="mb-4">Steve Wozniak</h4>
                                    <hr/>
                                    <p class="dark-grey-text mt-4">
                                        Co-Founder of the Apple computer science
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {#    <script>#}
    {#        $('.carousel').carousel()#}
    {#    </script>#}
    {#    <script>#}
    {#        $('#myCarousel').on('slide.bs.carousel', function () {#}
    {#            $('.carousel').carousel({#}
    {#                interval: 2000#}
    {#            })#}
    {#        })#}
    {#    </script>#}
{% endblock %}

templates/wishlist.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load my_tags %}
{% block content %}
    <div style="background-color: ghostwhite" id="about-title" class="p-5">
        <div class="container p-5">
            <h1 style="font-weight: bold; font-size: 50px; font-family: sans-serif;">Wishlist</h1>
        </div>
        <div class="container">
            <div class="row mt-5">
                {% for i in wishlist_products %}
                    {% if i %}
                    <div class="col-4 pb-5">
                        <div class="card" style="width: 18rem; height: 100%">
                            <img class="card-img-top" src="{{ i.image.url }}" alt="Card image cap" width="100%"
                                 height="50%">
                            <div class="card-body">
                                <a href="{% url 'products:product_detail' pk=i.pk %}"
                                   class="card-title">{{ i.title }}</a>
                                {% if i.is_new %}<span class="text-danger"> <i>
                                    <img width="10%" src="{% static 'images/new.png' %}" alt="">
                                </i></span>{% endif %}
                                <p class="card-text">{{ i.short_description }}</p>
                            </div>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item bold">${{ i.price }}{% if i.discount %}<span
                                        class="text-danger"> %{{ i.discount }}</span>
                                {% endif %}</li>
                            </ul>
                            <div class="card-body">
                                {% if i|in_wishlist:request.user %}
                                    <a href="{% url 'products:update-wishlist' pk=i.pk %}?next={{ request.path }}"
                                       class="heart card-link"><i></i><img width="10%" src="{% static 'images/heart.png' %}" alt=""></a>
                                {% else %}
                                    <a href="{% url 'products:update-wishlist' pk=i.pk %}?next={{ request.path }}"
                                       class="heart card-link"><i class="bi-heart"></i></a>
                                {% endif %}

                                <a href="#" class="card-link"><i class="bi-cart-plus"></i></a>
                                <a href="#"
                                   class="card-link"><i class="bi-star"></i></a><span
                                    class="bold">{{ i.rate }}</span>
                            </div>
                        </div>
                    </div>
                        {% else %}
                        <h1>No wishlist products...</h1>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}